<x-layouts.tailwind-app>
    @php($size = fn ($bytes) => number_format($bytes / 1024 / 1024, 2, ',', '.').' MB')
    <div class="mx-auto max-w-5xl space-y-6">
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow">
            <div class="relative overflow-hidden bg-gradient-to-br from-slate-950 via-indigo-950 to-violet-900 px-5 py-7 text-white sm:px-7 lg:py-8"><p class="text-xs font-bold tracking-[.16em] text-sky-200">KEAMANAN DATA OPERASIONAL</p><h1 class="mt-2 text-2xl font-bold sm:text-3xl">Backup dan Pemulihan Database Sekolah</h1><p class="mt-1 max-w-3xl text-base text-indigo-100">{{ $school->name }} · NPSN {{ $school->npsn }}. Backup hanya mencakup database lokal sekolah aktif.</p></div>
            <div class="flex flex-wrap items-center justify-between gap-3 px-6 py-4"><p class="text-base text-slate-600">Buat backup sebelum sinkronisasi besar, perubahan data massal, atau pemeliharaan aplikasi.</p><form method="POST" action="{{ route('school-backups.store') }}">@csrf<button class="rounded-lg bg-emerald-600 px-4 py-2.5 text-base font-bold text-white shadow hover:bg-emerald-700">Buat Backup Sekarang</button></form></div>
        </section>
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow">
            <div class="border-b border-slate-100 px-6 py-4"><h2 class="text-base font-bold text-slate-800">Riwayat Backup</h2><p class="mt-1 text-base text-slate-500">Pemulihan mengganti database aktif dengan salinan yang dipilih. Sistem membuat backup pengaman sebelum pemulihan.</p></div>
            <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-base"><thead class="bg-slate-50"><tr><th class="px-5 py-3 text-left text-xs font-bold uppercase text-slate-500">Waktu</th><th class="px-4 py-3 text-left text-xs font-bold uppercase text-slate-500">Berkas</th><th class="px-4 py-3 text-left text-xs font-bold uppercase text-slate-500">Jenis</th><th class="px-4 py-3 text-right text-xs font-bold uppercase text-slate-500">Ukuran</th><th class="px-5 py-3 text-right text-xs font-bold uppercase text-slate-500">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($backups as $backup)<tr><td class="px-5 py-4 text-slate-700">{{ $backup->created_at->translatedFormat('d F Y H:i') }}</td><td class="px-4 py-4 font-mono text-base text-slate-700">{{ $backup->file_name }}</td><td class="px-4 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-700">{{ str_replace('_', ' ', $backup->reason) }}</span></td><td class="px-4 py-4 text-right text-slate-700">{{ $size($backup->file_size) }}</td><td class="px-5 py-4 text-right"><form method="POST" action="{{ route('school-backups.restore', $backup->id) }}" data-confirm="Pulihkan database sekolah dari backup ini? Data saat ini akan diganti, tetapi sistem membuat backup pengaman terlebih dahulu.">@csrf<input type="hidden" name="confirm_restore" value="1"><button class="rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-base font-bold text-amber-800 hover:bg-amber-100">Pulihkan</button></form></td></tr>@empty<tr><td colspan="5" class="px-5 py-14 text-center text-slate-500">Belum ada backup. Buat backup pertama sekarang.</td></tr>@endforelse</tbody></table></div>
        </section>
    </div>
</x-layouts.tailwind-app>
