<x-layouts.tailwind-app>
    @php($rupiah = fn ($value) => 'Rp ' . number_format((float) $value, 0, ',', '.'))
    <div class="space-y-6">
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow">
            <div class="relative overflow-hidden bg-gradient-to-br from-slate-950 via-indigo-950 to-violet-900 px-5 py-7 text-white sm:px-7 lg:py-8"><p class="text-xs font-bold tracking-[.16em] text-sky-200">PUSAT DOKUMEN SPJ</p><h1 class="mt-2 text-2xl font-bold sm:text-3xl">Paket Dokumen SPJ</h1><p class="mt-1 max-w-3xl text-base text-indigo-100">Satu nomor bukti menjadi satu paket SPJ. Siapkan paket dari transaksi yang sudah memiliki rincian, kemudian tetapkan nomor dokumen.</p></div>
            <div class="grid divide-y divide-slate-100 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div class="px-5 py-4"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Transaksi Siap</p><p class="mt-1 text-xl font-bold text-slate-800">{{ number_format($readyTransactions, 0, ',', '.') }}</p></div><div class="px-5 py-4"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Paket Dibuat</p><p class="mt-1 text-xl font-bold text-violet-700">{{ number_format($totalPackages, 0, ',', '.') }}</p></div><div class="px-5 py-4"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Sudah Bernomor</p><p class="mt-1 text-xl font-bold text-emerald-700">{{ number_format($numberedPackages, 0, ',', '.') }}</p></div></div>
        </section>

        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow">
            <div class="border-b border-slate-100 px-5 py-4 sm:px-6"><h2 class="font-bold text-slate-800">Transaksi dan Paket SPJ</h2><p class="mt-1 text-base text-slate-500">Tombol siapkan hanya tersedia jika transaksi memiliki detail barang atau jasa.</p>
                <form method="GET" class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
                    <select name="month" class="rounded-lg border-slate-300 text-base"><option value="">Semua bulan</option>@foreach(['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'] as $index => $month)<option value="{{ $index + 1 }}" @selected(($filters['month'] ?? null) == $index + 1)>{{ $month }}</option>@endforeach</select>
                    <select name="quarter" class="rounded-lg border-slate-300 text-base"><option value="">Semua triwulan</option>@foreach(range(1,4) as $quarter)<option value="{{ $quarter }}" @selected(($filters['quarter'] ?? null) == $quarter)>Triwulan {{ $quarter }}</option>@endforeach</select>
                    <select name="spj_category" class="rounded-lg border-slate-300 text-base"><option value="">Semua jenis SPJ</option>@foreach($spjTypes as $type)<option value="{{ $type }}" @selected(($filters['spj_category'] ?? null) === $type)>{{ $type }}</option>@endforeach</select>
                    <select name="state" class="rounded-lg border-slate-300 text-base"><option value="all">Semua status</option><option value="ready" @selected(($filters['state'] ?? null) === 'ready')>Siap dibuat</option><option value="unprepared" @selected(($filters['state'] ?? null) === 'unprepared')>Belum disiapkan</option><option value="draft" @selected(($filters['state'] ?? null) === 'draft')>Draft paket</option><option value="numbered" @selected(($filters['state'] ?? null) === 'numbered')>Sudah bernomor</option></select>
                    <div class="flex gap-2"><button class="rounded-lg bg-violet-600 px-4 py-2 text-base font-bold text-white hover:bg-violet-700">Terapkan</button><a href="{{ route('spj.index', ['tab' => 'persiapan']) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-base font-semibold text-slate-600">Reset</a></div>
                </form>
            </div>
            <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-base"><thead class="bg-slate-50"><tr><th class="px-5 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-500">Nomor Bukti</th><th class="px-4 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-500">Uraian / Penerima</th><th class="px-4 py-3 text-center text-xs font-bold uppercase tracking-wide text-slate-500">Detail</th><th class="px-4 py-3 text-right text-xs font-bold uppercase tracking-wide text-slate-500">Nilai</th><th class="px-4 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-500">Status Dokumen</th><th class="px-5 py-3 text-right text-xs font-bold uppercase tracking-wide text-slate-500">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white">
                @forelse($transactions as $transaction)
                    <tr class="transition hover:bg-violet-50/50"><td class="px-5 py-4"><p class="font-mono font-bold text-violet-700">{{ $transaction->no_bukti }}</p><p class="mt-1 text-xs text-slate-500">{{ $transaction->transaction_date?->translatedFormat('d F Y') }}</p></td><td class="max-w-sm px-4 py-4"><p class="truncate font-semibold text-slate-800">{{ $transaction->payment_description ?: $transaction->description ?: 'Tanpa uraian' }}</p><p class="mt-1 truncate text-xs text-slate-500">{{ $transaction->recipient_name ?: 'Penerima belum diisi' }}</p></td><td class="px-4 py-4 text-center"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{{ $transaction->items_count }} item</span></td><td class="whitespace-nowrap px-4 py-4 text-right font-semibold text-slate-800">{{ $rupiah($transaction->gross_amount) }}</td><td class="px-4 py-4">@if($transaction->spjPackage)<span class="rounded-full {{ $transaction->spjPackage->document_number ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700' }} px-2.5 py-1 text-xs font-bold">{{ $transaction->spjPackage->document_number ? 'Bernomor' : 'Draft paket' }}</span><p class="mt-1 font-mono text-xs text-slate-500">{{ $transaction->spjPackage->document_number ?: 'Nomor belum ditetapkan' }}</p>@else<span class="text-xs font-medium text-slate-400">Belum disiapkan</span>@endif</td><td class="px-5 py-4 text-right">@if($transaction->spjPackage)<a href="{{ route('spj.index', ['tab' => 'paket', 'package_id' => $transaction->spjPackage->id]) }}" class="inline-flex rounded-lg border border-violet-200 bg-violet-50 px-3 py-2 text-xs font-bold text-violet-700 hover:bg-violet-100">Buka paket →</a>@elseif($transaction->items_count)<form method="POST" action="{{ route('spj.prepare', $transaction->id) }}">@csrf<button class="rounded-lg bg-violet-600 px-3 py-2 text-xs font-bold text-white shadow hover:bg-violet-700">Siapkan paket</button></form>@else<span class="text-xs text-slate-400">Rincian belum ada</span>@endif</td></tr>
                @empty<tr><td colspan="6" class="px-5 py-14 text-center"><p class="font-semibold text-slate-700">Belum ada transaksi tersinkron.</p><p class="mt-1 text-base text-slate-500">Jalankan Sinkron Semua ARKAS terlebih dahulu.</p></td></tr>@endforelse
            </tbody></table></div>
            <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 border-t border-slate-100 px-5 py-4 bg-slate-50/30">
                <x-page-table-per-page :total="$transactions->total()" />
                <div class="w-full sm:w-auto">{{ $transactions->links() }}</div>
            </div>
        </section>
    </div>
</x-layouts.tailwind-app>
