<div class="space-y-5">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-base font-bold text-[var(--ui-fg-strong)]">Sekolah yang tersedia</h2><p class="mt-1 text-sm text-[var(--ui-fg-muted)]">Cari berdasarkan nama sekolah atau NPSN, lalu pilih untuk melanjutkan.</p></div><p class="text-xs font-semibold text-[var(--ui-fg-muted)]">{{ $schools->count() }} sekolah</p></div>
    <label class="relative block"><span class="sr-only">Cari sekolah</span><x-ui.icon name="search" size="sm" class="pointer-events-none absolute left-3 top-1/2 z-10 -translate-y-1/2 text-[var(--ui-fg-muted)]" /><x-ui.input wire:model.live.debounce.300ms="search" placeholder="Cari nama sekolah atau NPSN..." class="pl-10" /></label>
    <div wire:loading wire:target="search" class="flex items-center gap-2 text-xs font-semibold text-[var(--theme-content-accent)]"><span class="h-3 w-3 animate-spin rounded-full border-2 border-[var(--theme-accent-soft)] border-t-[var(--theme-accent)]"></span>Memperbarui daftar...</div>
    <div class="space-y-3">
        @forelse($schools as $school)
            <article wire:key="school-{{ $school->id }}" class="group flex flex-col gap-4 rounded-2xl border border-[var(--ui-line)] bg-[var(--ui-surface-soft)] p-4 transition hover:border-[var(--theme-accent)] sm:flex-row sm:items-center sm:justify-between sm:p-5"><div class="flex min-w-0 items-start gap-3"><div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-[var(--ui-line)] bg-[var(--ui-surface-base)] text-[var(--theme-content-accent)]"><x-ui.icon name="school" size="md" /></div><div class="min-w-0"><h3 class="truncate font-bold text-[var(--ui-fg-strong)]">{{ $school->name }}</h3><p class="mt-1 text-xs text-[var(--ui-fg-muted)]">NPSN {{ $school->npsn }} <span class="px-1">·</span> Database {{ $school->databaseRecord?->status ?? 'Belum diprovisikan' }}</p></div></div><x-ui.button type="button" wire:click="selectSchool({{ $school->id }})" wire:loading.attr="disabled" wire:target="selectSchool({{ $school->id }})" icon="arrow-right" iconPosition="end" class="w-full justify-center sm:w-auto">Pilih sekolah</x-ui.button></article>
        @empty
            <div class="rounded-2xl border border-dashed border-[var(--ui-line-strong)] bg-[var(--ui-surface-soft)] px-5 py-10 text-center"><div class="mx-auto flex h-11 w-11 items-center justify-center rounded-full bg-[var(--ui-surface-muted)] text-[var(--ui-fg-muted)]"><x-ui.icon name="search" /></div><p class="mt-3 font-bold text-[var(--ui-fg-strong)]">Sekolah tidak ditemukan</p><p class="mt-1 text-sm text-[var(--ui-fg-muted)]">Coba gunakan nama atau NPSN yang berbeda.</p></div>
        @endforelse
    </div>
</div>
