<div class="space-y-5">
    @if (session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('success') }}</div>@endif
    <section class="overflow-hidden rounded-xl border border-[var(--ui-line)] bg-[var(--ui-surface-base)] shadow-sm">
        <div class="flex flex-col gap-3 border-b border-[var(--ui-line)] px-5 py-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="font-bold text-slate-800">Master Sekolah</h2><p class="mt-1 text-sm text-slate-500">Kelola identitas sekolah dan status database secara reaktif.</p></div><x-ui.input wire:model.live.debounce.300ms="search" placeholder="Cari sekolah, kode, atau NPSN..." /></div>
        <div class="divide-y divide-[var(--ui-line)]">@forelse($schools as $school)<div class="px-5 py-4"><p class="font-bold text-slate-800">{{ $school->name }}</p><p class="mt-1 text-sm text-slate-500">Kode {{ $school->school_code ?: '—' }} · NPSN {{ $school->npsn }} · {{ $school->regency ?: 'Kabupaten belum diisi' }}</p><span class="mt-2 inline-block rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">Database: {{ $school->databaseRecord?->status ?? 'Belum dibuat' }}</span></div>@empty<div class="px-5 py-10 text-center text-sm text-slate-500">Belum ada sekolah yang cocok.</div>@endforelse</div>
    </section>
    <x-ui.form-section title="Tambah Sekolah Baru" description="Daftarkan sekolah dan siapkan database operasionalnya tanpa reload halaman.">
        <form wire:submit="createSchool" class="space-y-4"><div class="grid gap-4 md:grid-cols-2"><x-ui.field label="Kode Sekolah" :error="$errors->first('schoolCode')" required><x-ui.input wire:model="schoolCode" maxlength="40" required /></x-ui.field><x-ui.field label="NPSN" :error="$errors->first('npsn')" required><x-ui.input wire:model="npsn" required /></x-ui.field><x-ui.field label="Nama Sekolah" class="md:col-span-2" :error="$errors->first('name')" required><x-ui.input wire:model="name" required /></x-ui.field><x-ui.field label="Alamat Sekolah"><x-ui.input wire:model="address" /></x-ui.field><x-ui.field label="Desa/Kelurahan"><x-ui.input wire:model="desa" /></x-ui.field><x-ui.field label="Kecamatan"><x-ui.input wire:model="district" /></x-ui.field><x-ui.field label="Kabupaten/Kota"><x-ui.input wire:model="regency" /></x-ui.field><x-ui.field label="Provinsi" class="md:col-span-2"><x-ui.input wire:model="province" /></x-ui.field></div><div class="flex justify-end"><x-ui.button type="submit">Tambah Sekolah</x-ui.button></div></form>
    </x-ui.form-section>
</div>
