<x-layouts.tailwind-app>
    <div class="mb-7 flex flex-wrap items-start justify-between gap-4">
        <div><h1 class="text-2xl font-bold tracking-tight text-slate-900">Penganggaran RKAS</h1><p class="mt-1 text-base text-slate-500">Pantau pagu RKAS dan realisasi BKU dari hasil sinkronisasi ARKAS.</p></div>
        <form method="post" action="{{ route('arkas.sync') }}" data-confirm="Sinkronisasi akan memperbarui data RKAS dan BKU dari ARKAS. Lanjutkan?">@csrf<input type="hidden" name="confirm_sync" value="1"><button class="rounded-lg bg-teal-600 px-4 py-2.5 text-base font-semibold text-white shadow hover:bg-teal-700">Sinkron Semua ARKAS</button></form>
    </div>
    <div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div class="rounded-2xl border border-indigo-100 bg-white p-5 shadow"><p class="text-xs font-bold tracking-wider text-slate-400">TOTAL ANGGARAN</p><p class="mt-2 text-2xl font-bold text-indigo-600">Rp {{ number_format($budget,0,',','.') }}</p><p class="mt-1 text-xs text-slate-500">RKAS tersinkron</p></div>
        <div class="rounded-2xl border border-teal-100 bg-white p-5 shadow"><p class="text-xs font-bold tracking-wider text-slate-400">REALISASI (BKU)</p><p class="mt-2 text-2xl font-bold text-teal-700">Rp {{ number_format($spent,0,',','.') }}</p><p class="mt-1 text-xs text-slate-500">belanja tercatat</p></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow"><p class="text-xs font-bold tracking-wider text-slate-400">SISA ANGGARAN</p><p class="mt-2 text-2xl font-bold {{ $remaining < 0 ? 'text-rose-600' : 'text-slate-700' }}">Rp {{ number_format(abs($remaining),0,',','.') }}</p><p class="mt-1 text-xs text-slate-500">{{ $remaining < 0 ? 'melewati anggaran' : 'belum direalisasikan' }}</p></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow"><p class="text-xs font-bold tracking-wider text-slate-400">KEGIATAN RKAS</p><p class="mt-2 text-2xl font-bold text-slate-800">{{ number_format($activityCount) }}</p><p class="mt-1 text-xs text-slate-500">kegiatan tersinkron</p></div>
    </div>
    <div class="mb-6 flex flex-wrap items-center gap-4 rounded-2xl border border-sky-200 bg-sky-50 p-5"><div class="rounded-xl bg-sky-600 px-3 py-2 text-base font-bold text-white">SISA TERSEDIA</div><div><p class="text-xs font-bold tracking-wider text-sky-700">MASIH BISA DIREALISASIKAN</p><p class="text-xl font-bold text-sky-900">Rp {{ number_format($underBudget,0,',','.') }}</p></div><div class="ml-auto flex gap-7 text-base"><div><p class="text-slate-500">Selisih sisa</p><strong class="text-emerald-700">Rp {{ number_format($underBudget,0,',','.') }}</strong></div><div><p class="text-slate-500">Selisih kurang</p><strong class="text-rose-600">Rp {{ number_format($overBudget,0,',','.') }}</strong></div></div></div>
    <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow"><div class="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold text-slate-800">Rincian Penganggaran RKAS</h2><p class="text-base text-slate-500">Cari, urutkan, dan atur jumlah baris langsung dari tabel.</p></div><div class="flex gap-2"><a class="rounded-lg border border-slate-300 px-3 py-2 text-base font-medium text-slate-600 hover:bg-slate-50" href="{{ route('synced-data.show','kegiatan') }}">Kegiatan</a><a class="rounded-lg border border-slate-300 px-3 py-2 text-base font-medium text-slate-600 hover:bg-slate-50" href="{{ route('synced-data.show','rkas') }}">Data Mentah</a></div></div><livewire:rkas-budget-table /></div>
</x-layouts.tailwind-app>
